# Generated by Django 3.0.4 on 2020-04-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acubook', '0002_bookinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinfo',
            old_name='Author',
            new_name='Authors',
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='Category',
            field=models.CharField(choices=[('Arts and Literature', 'Arts and Literature'), ('Science', 'Science'), ('Christian Books', 'Christian Books'), ('Nigerian and African Authors', 'Nigerian and African Authors'), ('Motivational', 'Motivational'), ('Business', 'Business'), ('Teen Books', 'Teen Books')], default='Arts and Literature', max_length=256),
        ),
    ]
