# Generated by Django 3.0.4 on 2020-04-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acubook', '0003_auto_20200427_2257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorys', models.CharField(choices=[('Arts and Literature', 'Arts and Literature'), ('Science', 'Science'), ('Christian Books', 'Christian Books'), ('Nigerian and African Authors', 'Nigerian and African Authors'), ('Motivational', 'Motivational'), ('Business', 'Business'), ('Teen Books', 'Teen Books')], default='Arts and Literature', max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='Category',
        ),
    ]
