# Generated by Django 3.0.4 on 2020-04-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acubook', '0004_auto_20200428_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='bookcategories',
            field=models.ManyToManyField(to='acubook.Category'),
        ),
    ]
