# Generated by Django 3.0.3 on 2020-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acubook', '0005_bookinfo_bookcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
