# Generated by Django 3.0.3 on 2020-05-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acubook', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='book',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
