# Generated by Django 3.0.7 on 2020-06-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acubook', '0008_auto_20200510_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='Book_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
